# Generated by Django 5.1.7 on 2025-03-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employee_submitted_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="employee_id",
        ),
    ]
