# Generated by Django 5.1.7 on 2025-04-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('driver', 'Driver'), ('driver_assistant', 'Driver Assistant'), ('warehouse_staff', 'Warehouse Staff'), ('inventory_manager', 'Inventory Manager')], default='staff', max_length=20),
        ),
    ]
