# Generated by Django 5.1.7 on 2025-03-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_remove_employee_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[
                    ("transport", "Transport"),
                    ("warehouse", "Warehouse"),
                    ("inventory", "Inventory"),
                ],
                max_length=100,
            ),
        ),
    ]
