# Generated by Django 5.1.7 on 2025-03-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employee_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="submitted_by",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="submitted_on",
        ),
    ]
