# Generated by Django 5.1.7 on 2025-03-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_remove_employee_submitted_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="user",
            new_name="role",
        ),
    ]
