# Generated by Django 5.1.7 on 2025-03-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_rename_user_employee_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="role",
            new_name="user",
        ),
    ]
