# Generated by Django 5.1.7 on 2025-03-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehousestock",
            name="inventory_item",
        ),
    ]
