# Generated by Django 5.1.7 on 2025-03-27 13:44

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Vehicle', 'Vehicle'), ('Fuel', 'Fuel'), ('Lubricant', 'Lubricant'), ('Machinery', 'Machinery'), ('Office Equipment', 'Office Equipment'), ('Stationery', 'Stationery'), ('Spare Parts', 'Spare Parts'), ('Tyres', 'Tyres'), ('Batteries', 'Batteries'), ('Tools', 'Tools'), ('Safety Gear', 'Safety Gear'), ('Warehouse Equipment', 'Warehouse Equipment'), ('Packaging Materials', 'Packaging Materials'), ('GPS Trackers', 'GPS Trackers'), ('Communication Devices', 'Communication Devices'), ('Hydraulic Fluids', 'Hydraulic Fluids'), ('Coolants', 'Coolants'), ('Load Securement', 'Load Securement'), ('Cargo Containers', 'Cargo Containers'), ('PPE', 'Personal Protective Equipment')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reorder_level', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, default=inventory.models.get_default_department, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol')], max_length=50)),
                ('storage_capacity', models.FloatField(help_text='Capacity in liters')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('Received', 'Received'), ('Issued', 'Issued'), ('Returned', 'Returned'), ('Transferred', 'Transferred'), ('Damaged', 'Damaged')], max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_ghana_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_position', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_out', to='departments.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_in', to='departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lubricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viscosity_grade', models.CharField(max_length=50)),
                ('application_area', models.CharField(max_length=255)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lubricants', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=100, unique=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinery', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100, unique=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_equipments', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('paper_size', models.CharField(blank=True, max_length=50, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationery_items', to='inventory.inventoryitem')),
            ],
        ),
    ]
