# Generated by Django 5.1.7 on 2025-03-27 14:12

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Trucks', 'Trucks'), ('Trailers', 'Trailers'), ('Pickup Trucks', 'Pickup Trucks'), ('Container Carriers', 'Container Carriers'), ('Heavy Duty Equipment', 'Heavy Duty Equipment'), ('Tankers', 'Tankers'), ('Dump Trucks', 'Dump Trucks'), ('Flatbed Trucks', 'Flatbed Trucks'), ('Vans', 'Vans'), ('Minivans', 'Minivans'), ('Panel Vans', 'Panel Vans'), ('Refrigerated Vans', 'Refrigerated Vans'), ('Buses', 'Buses'), ('Minibuses', 'Minibuses'), ('Coaches', 'Coaches'), ('Motorcycles', 'Motorcycles'), ('Scooters', 'Scooters'), ('Tricycles', 'Tricycles'), ('Auto Rickshaws', 'Auto Rickshaws'), ('Forklifts', 'Forklifts'), ('Cranes', 'Cranes'), ('Excavators', 'Excavators'), ('Bulldozers', 'Bulldozers'), ('Road Graders', 'Road Graders'), ('Tow Trucks', 'Tow Trucks'), ('Street Sweepers', 'Street Sweepers'), ('Wrecking Trucks', 'Wrecking Trucks'), ('Electric Vehicles', 'Electric Vehicles'), ('Hybrid Vehicles', 'Hybrid Vehicles'), ('Autonomous Vehicles', 'Autonomous Vehicles'), ('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('CNG', 'Compressed Natural Gas'), ('Engine Oil', 'Engine Oil'), ('Transmission Fluid', 'Transmission Fluid'), ('Hydraulic Oil', 'Hydraulic Oil'), ('Coolants', 'Coolants'), ('Brake Fluid', 'Brake Fluid'), ('Grease', 'Grease'), ('Tires', 'Tires'), ('Batteries', 'Batteries'), ('Brake Pads', 'Brake Pads'), ('Brake Discs', 'Brake Discs'), ('Clutch Kits', 'Clutch Kits'), ('Alternators', 'Alternators'), ('Starters', 'Starters'), ('Belts', 'Belts'), ('Filters', 'Filters'), ('Spark Plugs', 'Spark Plugs'), ('Radiators', 'Radiators'), ('Airbags', 'Airbags'), ('Exhaust Systems', 'Exhaust Systems'), ('Fuel Pumps', 'Fuel Pumps'), ('Transmission Systems', 'Transmission Systems'), ('Cargo Straps', 'Cargo Straps'), ('Chains and Binders', 'Chains and Binders'), ('Load Bars', 'Load Bars'), ('Pallets', 'Pallets'), ('Wooden Crates', 'Wooden Crates'), ('Plastic Containers', 'Plastic Containers'), ('Metal Containers', 'Metal Containers'), ('Cargo Nets', 'Cargo Nets'), ('Rope and Cordage', 'Rope and Cordage'), ('Dock Levelers', 'Dock Levelers'), ('Ramp Plates', 'Ramp Plates'), ('Jacks and Lifts', 'Jacks and Lifts'), ('Reflective Vests', 'Reflective Vests'), ('Helmets', 'Helmets'), ('Safety Gloves', 'Safety Gloves'), ('Safety Goggles', 'Safety Goggles'), ('First Aid Kits', 'First Aid Kits'), ('Fire Extinguishers', 'Fire Extinguishers'), ('Warning Triangles', 'Warning Triangles'), ('Emergency Lights', 'Emergency Lights'), ('Road Cones', 'Road Cones'), ('Speed Limit Signs', 'Speed Limit Signs'), ('Breathalyzers', 'Breathalyzers'), ('Seatbelts', 'Seatbelts'), ('GPS Devices', 'GPS Devices'), ('Telematics Systems', 'Telematics Systems'), ('Dashcams', 'Dashcams'), ('Two-Way Radios', 'Two-Way Radios'), ('Mobile Phones', 'Mobile Phones'), ('Vehicle Trackers', 'Vehicle Trackers'), ('RFID Scanners', 'RFID Scanners'), ('Computers', 'Computers'), ('Printers', 'Printers'), ('Office Chairs', 'Office Chairs'), ('Desks', 'Desks'), ('Paper Supplies', 'Paper Supplies'), ('Logbooks', 'Logbooks'), ('Invoices and Receipts', 'Invoices and Receipts'), ('Barcode Scanners', 'Barcode Scanners'), ('Handheld Devices', 'Handheld Devices'), ('Generators', 'Generators'), ('Air Compressors', 'Air Compressors'), ('Toolboxes', 'Toolboxes'), ('Power Tools', 'Power Tools'), ('Welding Equipment', 'Welding Equipment'), ('Mechanic Tools', 'Mechanic Tools'), ('Ladder and Stairs', 'Ladder and Stairs'), ('Storage Shelves', 'Storage Shelves'), ('Lighting Equipment', 'Lighting Equipment'), ('Warehouse Racks', 'Warehouse Racks'), ('Hand Trucks', 'Hand Trucks'), ('Pallet Jacks', 'Pallet Jacks'), ('Forklift Batteries', 'Forklift Batteries'), ('Conveyor Belts', 'Conveyor Belts'), ('Barcode Labels', 'Barcode Labels'), ('Industrial Scales', 'Industrial Scales'), ('Loading Dock Seals', 'Loading Dock Seals'), ('Towing Chains', 'Towing Chains'), ('Winches', 'Winches'), ('Spare Tires', 'Spare Tires'), ('Portable Battery Boosters', 'Portable Battery Boosters'), ('Tool Kits', 'Tool Kits'), ('Roadside Reflectors', 'Roadside Reflectors'), ('Jump Start Cables', 'Jump Start Cables'), ('Portable Fuel Containers', 'Portable Fuel Containers'), ('Refrigerated Containers', 'Refrigerated Containers'), ('Temperature Monitors', 'Temperature Monitors'), ('Insulated Coverings', 'Insulated Coverings'), ('Miscellaneous', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='department',
            field=models.ForeignKey(blank=True, default=inventory.models.get_default_department, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_out', to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_in', to='inventory.department'),
        ),
        migrations.CreateModel(
            name='StockReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField()),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ISSUE', 'Issue'), ('RETURN', 'Return'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('transaction_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
    ]
