# Generated by Django 5.1.7 on 2025-03-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("warehouse", "0002_remove_warehousestock_inventory_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Vehicle", "Vehicle"),
                    ("Fuel", "Fuel"),
                    ("Lubricant", "Lubricant"),
                    ("Machinery", "Machinery"),
                    ("Office Equipment", "Office Equipment"),
                    ("Stationery", "Stationery"),
                ],
                default="Vehicle",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="Warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="reorder_level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Fuel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[("Diesel", "Diesel"), ("Petrol", "Petrol")],
                        max_length=50,
                    ),
                ),
                ("storage_capacity", models.FloatField(help_text="Capacity in liters")),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuels",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lubricant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viscosity_grade", models.CharField(max_length=50)),
                ("application_area", models.CharField(max_length=255)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lubricants",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Machinery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_type", models.CharField(max_length=255)),
                ("manufacturer", models.CharField(max_length=255)),
                ("model_number", models.CharField(max_length=100, unique=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machinery",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfficeEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model_number", models.CharField(max_length=100, unique=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_equipments",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stationery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("paper_size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stationery_items",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
        ),
    ]
