# Generated by Django 5.1.7 on 2025-03-28 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
        ('inventory', '0004_alter_inventoryrequest_to_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_in', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_out', to='departments.department'),
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='department',
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('Received', 'Received'), ('Issued', 'Issued'), ('Returned', 'Returned'), ('Transferred', 'Transferred'), ('Damaged', 'Damaged')], max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_ghana_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_position', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to='employees.employee')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_out', to='departments.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_in', to='departments.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
