# Generated by Django 5.1.7 on 2025-03-28 08:18

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('inventory', '0005_alter_stocktransaction_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='department',
            field=models.ForeignKey(blank=True, default=inventory.models.get_default_department, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
