# Generated by Django 5.1.7 on 2025-04-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventoryrequest_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='transaction_type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Aborted', 'Aborted'), ('Issued', 'Issued'), ('Received', 'Received'), ('Returned', 'Returned'), ('Transferred', 'Transferred')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Aborted', 'Aborted'), ('Issued', 'Issued'), ('Received', 'Received'), ('Returned', 'Returned'), ('Transferred', 'Transferred')], max_length=20),
        ),
    ]
