# Generated by Django 5.1.7 on 2025-04-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_customuser_role'),
        ('inventory', '0010_alter_inventoryitem_category_and_more'),
        ('transport', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_approved', models.PositiveIntegerField(default=0)),
                ('transaction_type', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Aborted', 'Aborted'), ('Issued', 'Issued'), ('Received', 'Received'), ('Returned', 'Returned'), ('Transferred', 'Transferred')], max_length=20)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vehicle_requests', to='employees.employee')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_requests', to='inventory.inventoryitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_requests', to='employees.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requests', to='transport.vehicle')),
            ],
        ),
    ]
