# Generated by Django 5.1.7 on 2025-04-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Transport', 'Handles logistics, vehicle management, and transportation of goods.'), ('Warehouse', 'Manages storage, inventory control, and distribution of products.')], max_length=100, unique=True),
        ),
    ]
