# Generated by Django 5.1.7 on 2025-04-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Transport', 'Transport'), ('Warehouse', 'Warehouse')], max_length=100, unique=True),
        ),
    ]
