# Generated by Django 5.1.7 on 2025-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Transport', 'Transport'), ('Warehouse', 'Warehouse'), ('Procurement & Inventory Management', 'Procurement & Inventory Management')], max_length=100, unique=True),
        ),
    ]
