# Generated by Django 5.1.7 on 2025-03-24 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ghanacard_number', models.CharField(max_length=50, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry_date', models.DateField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('phone_2', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_join', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=128)),
                ('photo', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('reorder_level', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(editable=False, max_length=64, null=True, unique=True)),
                ('license_plate', models.CharField(max_length=128)),
                ('vehicle_type', models.CharField(choices=[('hatchback', 'HATCHBACK'), ('pickup', 'PICKUP'), ('suv', 'SUV'), ('sedan', 'SEDAN'), ('three wheeler', 'THREE_WHEELER'), ('trailer', 'TRAILER'), ('trailer_head', 'TRAILER_HEAD'), ('truck', 'TRUCK'), ('two wheeler', 'TWO_WHEELER')], max_length=64)),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('mileage', models.FloatField()),
                ('fuel_consumption', models.FloatField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'In Maintenance'), ('in_use', 'In Use')], max_length=20)),
                ('mfg_year_month', models.DateField(blank=True, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('vehicle_image', models.FileField(upload_to='uploads/images/vehicle/')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=100)),
                ('category', models.TextField(choices=[('general', 'General'), ('accident', 'Accident')], default='general')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.inventoryitem')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DrivervehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.driver')),
                ('assigned_vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DriverAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ghanacard_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('phone_2', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_join', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=128)),
                ('photo', models.CharField(max_length=256)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dispatched', 'Dispatched'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('trip_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.driver')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.driverassistant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantdrivervehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.driverassistant')),
                ('assigned_vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehicle')),
            ],
        ),
    ]
