# Generated by Django 5.1.7 on 2025-03-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_found', 'not_fount'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
