# Generated by Django 5.1.7 on 2025-03-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorytransaction",
            name="item",
        ),
        migrations.RemoveField(
            model_name="inventorytransaction",
            name="vehicle",
        ),
        migrations.DeleteModel(
            name="InventoryItem",
        ),
        migrations.DeleteModel(
            name="InventoryTransaction",
        ),
    ]
