# Generated by Django 5.1.7 on 2025-03-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0002_remove_inventorytransaction_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivervehicleassignment",
            name="assigned_assistant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transport.driverassistant",
            ),
        ),
    ]
